# Generated by Django 4.0.6 on 2022-07-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couch',
            name='full_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
